---
fixtures:
  symlinks:
    kibana5: "#{source_dir}"
  repositories:
    stdlib: https://github.com/puppetlabs/puppetlabs-stdlib.git
    apt: https://github.com/puppetlabs/puppetlabs-apt.git
    yamlfile: https://github.com/reidmv/puppet-module-yamlfile.git
