---
language: ruby
bundler_args: --without system_tests
script: "bundle exec rake release_checks"
matrix:
  allow_failures:
  fast_finish: true
rvm:
  - 2.1.10
  - 2.2.6
  - 2.3.3
  - 2.4.0
gemfile:
  - .gemfile
env:
  - PUPPET_VERSION="~> 4.8" STRICT_VARIABLES="yes"
notifications:
  email: false
